apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drillbook.name" . }}-config
  labels:
    {{- include "drillbook.labels" . | nindent 4 }}
data:
  drillbook.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
    state_dir: /state
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drillbook.name" . }}-drills
  labels:
    {{- include "drillbook.labels" . | nindent 4 }}
data:
  {{- range $name, $body := .Values.drills }}
  {{ $name }}: |
    {{- $body | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drillbook.name" . }}-runbooks
  labels:
    {{- include "drillbook.labels" . | nindent 4 }}
data:
  {{- range $name, $body := .Values.runbooks }}
  {{ $name }}: |
    {{- $body | nindent 4 }}
  {{- end }}
